datasets:
  feature_face_caption:
    data_type: images
    
    build_info:
      # image_path: /home/user/selected_face/first_face/images
      image_path: /home/user/selected_face/first_face/first_frames

      ann_path: /home/user/selected_face/face_emotion/relative_train_NCEV.txt
      # ann_path: /home/user/selected_face/face_emotion/all_label_NCEV.txt
      # ann_path: /home/user/selected_face/face_emotion/target_label_list_0512_smp.txt
